name: Release

on:
  push:
    branches: [ "main" ]   # semantic-release runs on main and decides if a release is needed
  workflow_dispatch:

permissions:
  contents: write          # semantic-release pushes version bump + tag
  id-token: write          # REQUIRED for PyPI Trusted Publisher (OIDC)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release build

      # Decide next version, bump pyproject.toml, create tag and GitHub release
      - name: semantic-release version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release version

      - name: Build sdist and wheel
        run: python -m build

      # Publish to PyPI using OIDC Trusted Publisher
      - name: Publish to PyPI (Trusted Publisher)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          # environment: production   # uncomment if you specified an Environment name on PyPI

